### ISSUE TITLE
BUG: Delete Student not working

### ISSUE THREAD

**Issue by abhishek-2810** [nitin16112004/LibraryManagement#8]
Student is not getting deleted when given StudentID

output screen:
Library Management System
1. Add Student
2. Add Book
3. Get Student Info
4. Get Book Info
5. Delete Student
6. Delete Book
7. View Library Summary
8. Exit
Enter your choice: 3
Student ID: 1, First Name: Abhishek, Last Name: Verma, Email: 28a.v10@gmail.com, Phone No: 9818918299
Student ID: 2, First Name: Nitin, Last Name: Verma, Email: nitin@gmail.com, Phone No: 9818918290

Library Management System
1. Add Student
2. Add Book
3. Get Student Info
4. Get Book Info
5. Delete Student
6. Delete Book
7. View Library Summary
8. Exit
Enter your choice: 5
Enter Student ID to delete: 1
Student ID: 1, First Name: Abhishek, Last Name: Verma, Email: 28a.v10@gmail.com, Phone No: 9818918299 has been removed
Student ID 1 not found

Library Management System
1. Add Student
2. Add Book
3. Get Student Info
4. Get Book Info
5. Delete Student
6. Delete Book
7. View Library Summary
8. Exit
Enter your choice: 3
Student ID: 1, First Name: Abhishek, Last Name: Verma, Email: 28a.v10@gmail.com, Phone No: 9818918299
Student ID: 2, First Name: Nitin, Last Name: Verma, Email: nitin@gmail.com, Phone No: 9818918290

**Comment by nitin16112004** [comment]
Now you check it i will fix it the BUG

**Comment by abhishek-2810** [comment]
still facing an issue in delete student

Output screen:
Library Management System
1. Add Student
2. Add Book
3. Get Student Info
4. Get Book Info
5. Delete Student
6. Delete Book
7. Update Student Details
8. Update Book Details
9. Exit
Enter your choice: 5
Enter Student ID to delete: 3
Student ID not found
Student ID not found
Student with ID 3 has been removed

**Comment by abhishek-2810** [comment]
These are students available
Student ID: 1, First Name: Abhishek, Last Name: Verma, Email: 28a.v10@gmail.com, Phone No: 9818918299
Student ID: 2, First Name: Nitin, Last Name: Verma, Email: nitin@gmail.com, Phone No: 9818918299

While Updating details for Student ID 2, I am getting following error
Library Management System
1. Add Student
2. Add Book
3. Get Student Info
4. Get Book Info
5. Delete Student
6. Delete Book
7. Update Student Details
8. Update Book Details
9. Exit
Enter your choice: 7
Enter Student ID to update:2
Enter New First Name:
Enter New Last Name:Singh
Enter New Email:
Enter New Phone No.:
Traceback (most recent call last):
  File "D:\LibraryManagement\LibraryMangement.py", line 83, in <module>
    phoneNo = int(input("Enter New Phone No.:")) or student.PhoneNo
              ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

**Comment by abhishek-2810** [comment]
Fixed
